
function checkNumber(num) {
    return new Promise((resolve, reject) => {
        if (typeof num !== "number") {
            reject(" Not a valid number");
        } else if (num % 2 === 0) {
            resolve(`${num} ➝ Even`);
        } else {
            resolve(`${num} ➝ Odd`);
        }
    });
}


async function run() {
    try {
        let result1 = await checkNumber(4);
        console.log(result1);

        let result2 = await checkNumber(7);
        console.log(result2);

        let result3 = await checkNumber("hello"); 
        console.log(result3);
    } catch (error) {
        console.error("Caught Error:", error);
    } finally {
        console.log(" Finished checking numbers");
    }
}

// Run the async function
run();
